# -*- coding: utf-8 -*-
"""Copy of Basic_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoC47lks2P7m05A4Qw75oBY1ybTyI94B
"""

# =====================================================================
# PHASE 1: THE COLLEGE FINDER (Variables, Operators, & Dictionaries)
# =====================================================================
print("==================================================")
print("🎓 WELCOME TO THE KERALA HIGHER EDUCATION PORTAL 🎓")
print("==================================================")

# 1. Capture user information dynamically using input() and Type Casting
student_name = input("Enter your full name: ").strip()

# Casting the input text directly into a decimal Float number for comparisons
marks_12th = float(input("Enter your 12th Board Exam percentage (e.g., 85.5): "))

print(f"\nHello {student_name}! Scanning available colleges based on your marks...")

# 2. Creating a dictionary of college tiers using conditions
# High marks unlock premium seats; average marks unlock tier-2 seats
if marks_12th >= 85.0:
    print("🌟 Status: You qualify for Premium Tier-1 Government Colleges!")
    available_colleges = {
        1: "College of Engineering, Trivandrum (CET)",
        2: "Government Engineering College, Thrissur",
        3: "Calicut Medical College"
    }
elif marks_12th >= 60.0:
    print("👍 Status: You qualify for Tier-2 Merit-Aided Colleges!")
    available_colleges = {
        1: "VIT Campus, Bangalore",
        2: "Model Engineering College, Ernakulam",
        3: "TKM College of Engineering, Kollam"
    }
else:
    print("⚠️ Status: You qualify for Tier-3 Private/Self-Financing Colleges.")
    available_colleges = {
        1: "Malabar Institute of Technology",
        2: "Kerala Rural Technical Campus",
        3: "City Institute of Science"
    }

# 3. Using a For-Loop to print out the dictionary options dynamically
print("\n--- AVAILABLE COLLEGES FOR YOU ---")
for choice_id, college_name in available_colleges.items():
    print(f" Press {choice_id} to select: {college_name}")

# User inputs their choice index code
selected_college_id = int(input("\nEnter the number of the college you want to join: "))
my_college = available_colleges[selected_college_id]

print(f"\n🎯 Selected Destination: {my_college}")

# =====================================================================
# PHASE 2: DEGREE SELECTION & PROFILE CREATION (Lists & Conditionals)
# =====================================================================
print("\n" + "="*50)
print("📋 PHASE 2: APPLICATION & PROFILE BUILDER")
print("="*50)

print("Available Fields of Study:\n 1. Computer Science (CS)\n 2. Electronics (EC)\n 3. Medical (MED)")
degree_choice = input("Type your preferred degree branch choice (CS/EC/MED): ").strip().upper()

# We start an empty application tracking list to collect custom student fields
student_profile_data = [student_name, marks_12th, my_college, degree_choice]

# Branch-Specific Logic: Every degree asks for different custom details!
if degree_choice == "CS":
    has_laptop = input("Do you own a laptop for coding labs? (yes/no): ").strip().lower()
    preferred_language = input("Enter your preferred programming language (e.g., Python): ").strip()
    # Adding items dynamically to our profile array list container
    student_profile_data.append(has_laptop)
    student_profile_data.append(preferred_language)

elif degree_choice == "EC":
    soldering_kit_owned = input("Do you possess an electronics hardware toolkit? (yes/no): ").strip().lower()
    math_elective = input("Enter your preferred engineering math track (Pure/Applied): ").strip()
    student_profile_data.append(soldering_kit_owned)
    student_profile_data.append(math_elective)

elif degree_choice == "MED":
    blood_group = input("Enter your official blood group (e.g., O+): ").strip().upper()
    stethoscope_ordered = input("Have you pre-ordered your medical lab coat? (yes/no): ").strip().lower()
    student_profile_data.append(blood_group)
    student_profile_data.append(stethoscope_ordered)

else:
    print("❌ Invalid stream selected! Defaulting profile parameters to General.")
    student_profile_data.append("No special requirements specified.")

print(f"\n📂 Registration Profile Compiled into List: {student_profile_data}")

# =====================================================================
# PHASE 3: THE COLLEGE ENTRANCE EXAM QUIZ (Loops & Counters)
# =====================================================================
print("\n" + "="*50)
print("📝 PHASE 3: LIVE COLLEGE ADMISSION ENTRANCE TEST")
print("="*50)
print("To verify your past performance, you must answer 2 basic field questions.")

quiz_score = 0  # Initialize a tracking variable counter for correct answers

if degree_choice == "CS":
    print("\n[Question 1]: What data structure uses square brackets '[ ]' and can be changed?")
    ans1 = input("Your answer (list/tuple/set): ").strip().lower()
    if ans1 == "list":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The correct answer was 'list'.")

    print("\n[Question 2]: Which loop runs indefinitely while a condition remains True?")
    ans2 = input("Your answer (for/while): ").strip().lower()
    if ans2 == "while":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The correct answer was 'while'.")

elif degree_choice == "EC":
    print("\n[Question 1]: What electrical safety device melts to break an overloaded circuit?")
    ans1 = input("Your answer (fuse/resistor/switch): ").strip().lower()
    if ans1 == "fuse":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The correct answer was 'fuse'.")

    print("\n[Question 2]: True or False: A resistor increases the flow of electrical current.")
    ans2 = input("Your answer (true/false): ").strip().lower()
    if ans2 == "false":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The statement is False.")

else: # Medical or default general branch questions
    print("\n[Question 1]: Which primary organ is responsible for pumping blood through the human body?")
    ans1 = input("Your answer (heart/lungs/brain): ").strip().lower()
    if ans1 == "heart":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The answer was 'heart'.")

    print("\n[Question 2]: Which dynamic data structure is contained inside a cell nucleus?")
    ans2 = input("Your answer (dna/rna/protein): ").strip().lower()
    if ans2 == "dna":
        print("✅ Correct!"); quiz_score += 1
    else: print("❌ Wrong! The answer was 'dna'.")

# =====================================================================
# PHASE 4: FINAL SELECTION MATRIX & SYLLABUS DISPATCH (Tuples & Sets)
# =====================================================================
print("\n" + "="*50)
print("🏁 PHASE 4: FINAL ADMISSION EVALUATION RESULTS")
print("="*50)

# We check BOTH their high school marks AND their live entrance quiz score performance
if marks_12th >= 60.0 and quiz_score >= 1:
    print(f"🎉 CONGRATULATIONS {student_name}!!! 🎉")
    print(f"You have been officially SELECTED for admission into {my_college}!")
    print("Welcome to your academic journey ahead.\n")

    # 1. Dispatching an unchangeable timetable schedule using a secure Tuple
    print("--- 📅 YOUR IMMUTABLE 1ST SEMESTER TIMETABLE ---")
    college_timetable = ("09:00 AM - Core Theory Lecture", "01:00 PM - Lunch Hour Break", "02:00 PM - Practical Lab Workshop")

    # Unpacking the tuple cleanly for display purposes
    morning_slot, lunch_slot, afternoon_slot = college_timetable
    print(f" 🟢 Morning: {morning_slot}\n 🟡 Midday:  {lunch_slot}\n 🔵 Afternoon: {afternoon_slot}\n")

    # 2. Dispatching a clean unique syllabus using a Set (Eliminates duplicate module alerts)
    print("--- 📚 UNIFORM SYLLABUS COURSE MODULES REGISTERED ---")
    if degree_choice == "CS":
        syllabus_set = {"Introduction to Python", "Data Structures Fundamentals", "Digital Design Systems"}
    elif degree_choice == "EC":
        syllabus_set = {"Circuit Simulation Logic", "Basic Semiconductor Theory", "Engineering Mathematics"}
    else:
        syllabus_set = {"Human Anatomy Foundations", "Cell Biology Essentials", "Medical Chemistry Labs"}

    # Printing out the course tracks using an automated for-loop scanner
    for course in syllabus_set:
        print(f" ✅ Registered Module: {course}")

    print("\n🚀 We wish you a happy, successful journey ahead in your professional career!")

else:
    print(f"💔 Admission Result Status: REJECTED.")
    print("Reason: Your combined 12th percentage or entrance examination quiz score did not meet criteria.")
    print(f"Action Required: Please run the program application engine again and try a different tier of colleges.")

print("\n" + "="*50)
print("--- 📴 APPLICATION PROCESS COMPLETE: TERMINATING SESSION ---")
print("="*50)